/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM_package;
import SGBD_Request_Package.Mariadb_Request;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author Guillaume
 */
public class Add_Data_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Add_Data_Panel
     */
    public Add_Data_Panel() {
        initComponents();
        
        // Initialisation des listes permettant de choisir les dates.
        
        // Initialisation des jours
        for (int i = 31; i >= 1; i--) {     
            
            if(String.valueOf(i).length() < 2){
                jCB_day.addItem('0'+String.valueOf(i)); 
            }
            else{
                jCB_day.addItem(String.valueOf(i)); 
            }
                                
        }
        
        // Initialisation des mois
        for (int i = 12; i >= 1; i--) {        
            if(String.valueOf(i).length() < 2){
                jCB_month.addItem('0'+String.valueOf(i)); 
            }
            else{
                jCB_month.addItem(String.valueOf(i)); 
            }         
        }
        
        // Initialisation des années
        for (int i = 2021; i >= 1920; i--) {        
            jCB_year.addItem(String.valueOf(i));           
        }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_Services = new javax.swing.JList<>();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jCB_day = new javax.swing.JComboBox<>();
        jCB_month = new javax.swing.JComboBox<>();
        jCB_year = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(66, 130, 196));
        jLabel9.setText("Service :");

        jList_Services.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jList_Services.setForeground(new java.awt.Color(51, 51, 51));
        jList_Services.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Service Informatique", "Service Qualite", "Service Juridique", "Service Comptabilité", "Service Ressources Humaines", "Service Commercial", "Service Direction", "Service Maintenance", "Atelier de Production" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_Services.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList_Services);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(66, 130, 196));
        jLabel11.setText("Prénom :");

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(51, 51, 51));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(66, 130, 196));
        jLabel12.setText("Adresse électronique :");

        jLabel13.setBackground(new java.awt.Color(66, 130, 196));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Formulaire de création du profil de l'employé");
        jLabel13.setOpaque(true);

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(51, 51, 51));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(66, 130, 196));
        jLabel8.setText("Nom :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(66, 130, 196));
        jLabel14.setText("Date de naissance :");

        jButtonAdd.setBackground(new java.awt.Color(66, 130, 196));
        jButtonAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("Ajouter l'utilisateur");
        jButtonAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddMouseClicked(evt);
            }
        });

        jCB_day.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jCB_day.setForeground(new java.awt.Color(51, 51, 51));

        jCB_month.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jCB_month.setForeground(new java.awt.Color(51, 51, 51));

        jCB_year.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jCB_year.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6)
                    .addComponent(jTextField5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCB_day, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB_month, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB_year, 0, 78, Short.MAX_VALUE))
                    .addComponent(jTextField3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCB_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCB_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCB_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    // Contrôle de la date.
    private boolean CheckDate(String p_DateToCheck){
        
        boolean check;
              
        try{
            
            // Parsing de la date : si il échoue, la date n'existe pas. 
            LocalDate.parse(p_DateToCheck,DateTimeFormatter.ofPattern("uuuu-M-d")
            .withResolverStyle(ResolverStyle.STRICT));
            
            // Si le parsing s'est déroulé correctement, le booleen passe à true
            check = true;
            
            // Gestion de l'erreur
        } catch(DateTimeParseException e) {
            e.printStackTrace();
            check = false;
        }
        
        return check;
    }
    
    // Evenement de clique sur le bouton d'ajout.
    private void jButtonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseClicked
        // TODO add your handling code here:
        
        // Obtention des éléments saisis par l'utilisateur
        String nom = jTextField3.getText();
        String prenom = jTextField5.getText();
        String email = jTextField6.getText();
        
        String day = jCB_day.getSelectedItem().toString();
        String month = jCB_month.getSelectedItem().toString();
        String year = jCB_year.getSelectedItem().toString();
        
        String dateOfBirth = year + '-' + month + '-' + day;      
        String service = jList_Services.getSelectedValue();
               
        // Vérification des informations entrées par l'utilisateur.
        
        // Booleen permettant de valider les données. 
        boolean dataCheckOk = true;
        
        // Vérification du format du mail.
        if (!email.matches("^.+@.+\\..+$")){
            // Message d'erreur.
            JOptionPane.showMessageDialog(null, "La forme de l'email est incorrecte. Veuillez respecter cette forme : abc...@xxxx.fr" , "Email incorrect", JOptionPane.INFORMATION_MESSAGE);
            dataCheckOk = false;
        }
        
        // Vérification du format du nom.
        if (!nom.matches("^[A-Z][a-zA-Z\\-\\ ]+{20}")){
            JOptionPane.showMessageDialog(null, "La forme du nom est incorrect : il doit contenir une majuscule pour la première lettre, puis uniquement des caractères minuscules, espace ou \"-\"." , "Nom incorrect", JOptionPane.INFORMATION_MESSAGE);
            dataCheckOk = false;
        }
        
        // Vérification du format du prénom.
        if (!prenom.matches("^[A-Z][a-zA-Z\\-\\ ]+{20}")){
            JOptionPane.showMessageDialog(null, "La forme du prénom est incorrect : il doit contenir une majuscule pour la première lettre, puis uniquement des caractères minuscules, espace ou \"-\"." , "Prénom incorrect", JOptionPane.INFORMATION_MESSAGE);
            dataCheckOk = false;
        }
        
        // Vérification du format de la date avec l'appel de la méthode précédente.
        if(!CheckDate(dateOfBirth)){
            JOptionPane.showMessageDialog(null, "La date est incorrecte, veuillez sélectionner une date existante." , "Date incorrecte", JOptionPane.INFORMATION_MESSAGE);
            dataCheckOk = false;
        }
        
        // Vérification de la sélection d'un élément de la liste.
        if(jList_Services.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Vous n'avez pas sélectionné de service." , "Aucun service", JOptionPane.INFORMATION_MESSAGE);
            dataCheckOk = false;
        }
         
        // Si le booléen est toujours à true, la donnée est ajoutée. 
        if (dataCheckOk) {         
            Mariadb_Request.Add_Data(nom, prenom, email, dateOfBirth, service);
            JFrame Frame = (JFrame) SwingUtilities.getWindowAncestor(this);       
            Frame.dispose();
        }    
    }//GEN-LAST:event_jButtonAddMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JComboBox<String> jCB_day;
    private javax.swing.JComboBox<String> jCB_month;
    private javax.swing.JComboBox<String> jCB_year;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList_Services;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
