/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM_package;

import SGBD_Request_Package.Mariadb_Request;
import java.awt.event.WindowEvent;
import java.util.List;

/**
 *
 * @author Guillaume
 */
public class Menu_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Panel
     */
    public Menu_Panel() {
        initComponents();      
        UpdateComboBox(); // Récupération des éléments à placer dans la liste.       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_add = new javax.swing.JButton();
        jButton_del = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_user = new javax.swing.JComboBox<>();
        jButton_validUser = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jButton_add.setBackground(new java.awt.Color(66, 130, 196));
        jButton_add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add.setText("Ajouter un salarié");
        jButton_add.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_addMouseClicked(evt);
            }
        });

        jButton_del.setBackground(new java.awt.Color(66, 130, 196));
        jButton_del.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_del.setForeground(new java.awt.Color(255, 255, 255));
        jButton_del.setText("Supprimer un salarié");
        jButton_del.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_delMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 130, 196));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Affichez le profil d'un utilisateur :");

        jComboBox_user.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jComboBox_user.setForeground(new java.awt.Color(66, 130, 196));

        jButton_validUser.setBackground(new java.awt.Color(66, 130, 196));
        jButton_validUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_validUser.setForeground(new java.awt.Color(255, 255, 255));
        jButton_validUser.setText("Valider");
        jButton_validUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_validUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_validUserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_del, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_user, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton_validUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_del, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_validUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Evenement de clique sur le bouton d'ajout
    private void jButton_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_addMouseClicked
        // TODO add your handling code here:
        
        // Appel du constructeur du formulaire d'ajout
        Add_Data_Form addDataF = new Add_Data_Form();

        /*
        Création d'un événément permettant de mettre à jour le selecteur des 
        utilisateurs lors de la fermeture du formulaire.
        Les utilisateurs sont ainsi "à jour".
        */
        
        addDataF.addWindowListener(new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosed(WindowEvent e) {
                UpdateComboBox();
            }   
        });   
        
        // La fenetre devient visible.
        addDataF.setVisible(true);
    }//GEN-LAST:event_jButton_addMouseClicked

    // Evenement de clique sur le bouton de suppression
    private void jButton_delMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_delMouseClicked
        // TODO add your handling code here:      
        
        // Appel du constructeur du formulaire de suppression
        Del_Data_Form delDataF = new Del_Data_Form();
                
        /*
        Création d'un événément permettant de mettre à jour le selecteur des 
        utilisateurs lors de la fermeture du formulaire.
        Les utilisateurs sont ainsi "à jour".
        */
        
        delDataF.addWindowListener(new java.awt.event.WindowAdapter() {
                             
            @Override
            public void windowClosed(WindowEvent e) {
                UpdateComboBox();
            }   
        }); 
        
        // La fenetre devient visible.
        delDataF.setVisible(true);     
    
    }//GEN-LAST:event_jButton_delMouseClicked

    // Evenement de clique sur le bouton validant l'utilisateur à afficher
    private void jButton_validUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_validUserMouseClicked
        // TODO add your handling code here:
        
        // Appel du constructeur et apparition de la fenêtre
        User_Info_Form userInfForm = new User_Info_Form(jComboBox_user.getSelectedItem().toString());
        userInfForm.setVisible(true);
        
    }//GEN-LAST:event_jButton_validUserMouseClicked

    // Mise à jour de la liste des utilisateurs.
    private void UpdateComboBox()
    {
        // Appel de la méthode permettant d'effectuer la requête.
        List<String[]> resList = Mariadb_Request.Get_Name();  
        
        if(!resList.isEmpty()){
            String[] element;
            // Suppression des éléments pour préparer la mise à jour.
            jComboBox_user.removeAllItems();
            // Ajout à la liste des éléments anciens et nouveaux.
            for (int i = 1; i < resList.size(); i++) {
                element = resList.get(i); 
                jComboBox_user.addItem(element[0] + ' ' + element[1]);           
            }   
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_del;
    private javax.swing.JButton jButton_validUser;
    private javax.swing.JComboBox<String> jComboBox_user;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}