/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM_package;

import SGBD_Request_Package.Mariadb_Request;

/**
 *
 * @author Guillaume
 */
public class User_Info_Panel extends javax.swing.JPanel {

    /**
     * Creates new form User_Info_Panel
     */
    public User_Info_Panel() {
        initComponents();
    }

    public User_Info_Panel(String p_userName) {
        initComponents();
        
        // Appel de la méthode permettant l'obtention des infos d'un utilisateur
        String[] userInfo = Mariadb_Request.Get_User(p_userName);
         
        if(userInfo.length != 0){
        
            // Ajout des infos aux labels du panneau.
            jLabel_DisplayName.setText(userInfo[0]);
            jLabel_Display_FirstName.setText(userInfo[1]);
            jLabel_DisplayEmail.setText(userInfo[2]);
            jLabel_DisplayDoB.setText(userInfo[3]);
            jLabel_DisplayService.setText(userInfo[4]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jLabel_DisplayName = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabel_Display_FirstName = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabel_DisplayEmail = new javax.swing.JLabel();
        jLabelDoB = new javax.swing.JLabel();
        jLabel_DisplayDoB = new javax.swing.JLabel();
        jLabelService = new javax.swing.JLabel();
        jLabel_DisplayService = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabelName.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(66, 130, 196));
        jLabelName.setText("Nom :");

        jLabel_DisplayName.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel_DisplayName.setText("jLabel3");

        jLabelFirstName.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabelFirstName.setForeground(new java.awt.Color(66, 130, 196));
        jLabelFirstName.setText("Prénom :");

        jLabel_Display_FirstName.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Display_FirstName.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel_Display_FirstName.setText("jLabel5");

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(66, 130, 196));
        jLabelEmail.setText("Courriel :");

        jLabel_DisplayEmail.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_DisplayEmail.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel_DisplayEmail.setText("jLabel7");

        jLabelDoB.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabelDoB.setForeground(new java.awt.Color(66, 130, 196));
        jLabelDoB.setText("Date de Naissance :");

        jLabel_DisplayDoB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel_DisplayDoB.setText("jLabel9");

        jLabelService.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabelService.setForeground(new java.awt.Color(66, 130, 196));
        jLabelService.setText("Service :");

        jLabel_DisplayService.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_DisplayService.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel_DisplayService.setText("jLabel11");

        jLabel1.setBackground(new java.awt.Color(66, 130, 196));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Profil du salarié");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelService)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_DisplayService, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelDoB)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel_DisplayDoB, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelEmail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel_DisplayEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelFirstName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel_Display_FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel_DisplayName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jLabel_DisplayName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstName)
                    .addComponent(jLabel_Display_FirstName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabel_DisplayEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDoB)
                    .addComponent(jLabel_DisplayDoB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelService)
                    .addComponent(jLabel_DisplayService))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDoB;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelService;
    private javax.swing.JLabel jLabel_DisplayDoB;
    private javax.swing.JLabel jLabel_DisplayEmail;
    private javax.swing.JLabel jLabel_DisplayName;
    private javax.swing.JLabel jLabel_DisplayService;
    private javax.swing.JLabel jLabel_Display_FirstName;
    // End of variables declaration//GEN-END:variables
}
